# NOTE: Use the docker-up-local.sh bash script to actually docker up the local environment
# NOTE: This is meant for creating a local/entirely contained docker environment
version: "3.8"
services:
  player-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: player-es
    ports:
      - 1792:9200
    environment:
      - discovery.type=single-node
    healthcheck:
      interval: 9s
      retries: 2
      timeout: 7s
      test: curl --fail -s http://player-es:9200/_cat/health || exit 1
  player-api:
    build:
      context: .
      args:
        buildconfig: Release
      dockerfile: ./Dockerfile
    restart: on-failure
    container_name: player-api
    ports:
      - 8082:8082
    environment:
      PLAYERS_CONNECTIONSTRINGS__ELASTICSEARCH: http://player-es:9200
    depends_on:
      - player-es
    healthcheck:
      interval: 99s
      retries: 2
      timeout: 19s
      test: curl --fail -s http://localhost:8082/ping || exit 1
